sudo: required
dist: trusty

language: node_js
node_js:
  - '7.2.1'

install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get update -q
  - sudo apt-get install -q google-chrome-stable


before_script:

  - npm install
  - npm run preupdate-webdriver
  - 'node_modules/protractor/bin/webdriver-manager update'
  - 'node_modules/protractor/bin/webdriver-manager start 2>&1 &'
  - sleep 3

script:
  - npm run start
  - npm run test-single-run
  - npm run protractor
